version: "3.8"

services:
  db:
    image: mysql/mysql-server:5.7
    ports:
      - "3305:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASS}"
      - "MYSQL_DATABASE=${DB_NAME}"
  web:
    container_name: api
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
    depends_on:
      - db
    links:
      - "db:database"
